# Use the official Nginx image
FROM nginx:alpine

# Copy custom Nginx configuration
COPY default.conf.tpl /etc/nginx/conf.d/default.conf

# Expose the port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
